name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: build
      run: ./gradlew build

    - name: create docker image
      run: docker build -t docker.pkg.github.com/pmauduit/sentry-frontend/sentry-frontend:latest .

    - name: login on github packages repository
      run: echo $DOCKER_PASSWORD | docker login https://docker.pkg.github.com -u pmauduit --password-stdin
      env:
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  
    - name: publish the docker image
      run: docker push docker.pkg.github.com/pmauduit/sentry-frontend/sentry-frontend:latest
